# Generated by Django 5.2.8 on 2025-11-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemist', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
